version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test:unit
      - run:
          command: npm run test:int:circleci
workflows:
    build-and-test:
      jobs:
        - test